// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1vMHy-b0VGS8-R_lNU5UHaIGFvrQoZ0Y',
    appId: '1:210743138752:web:cbdf32066ebfe9e3b95025',
    messagingSenderId: '210743138752',
    projectId: 'liverunxi',
    authDomain: 'liverunxi.firebaseapp.com',
    storageBucket: 'liverunxi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5FoWjTcXu_q-VOzi2WKNbzH5ZgBYJ9OM',
    appId: '1:210743138752:android:692c12735ed42f46b95025',
    messagingSenderId: '210743138752',
    projectId: 'liverunxi',
    storageBucket: 'liverunxi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuZjlXywWydjEgLUxX8ugRY0Bv_gucC14',
    appId: '1:210743138752:ios:9a4b65085de8043ab95025',
    messagingSenderId: '210743138752',
    projectId: 'liverunxi',
    storageBucket: 'liverunxi.firebasestorage.app',
    iosBundleId: 'com.example.liverunXi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuZjlXywWydjEgLUxX8ugRY0Bv_gucC14',
    appId: '1:210743138752:ios:9a4b65085de8043ab95025',
    messagingSenderId: '210743138752',
    projectId: 'liverunxi',
    storageBucket: 'liverunxi.firebasestorage.app',
    iosBundleId: 'com.example.liverunXi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1vMHy-b0VGS8-R_lNU5UHaIGFvrQoZ0Y',
    appId: '1:210743138752:web:9c7ca5510215fff7b95025',
    messagingSenderId: '210743138752',
    projectId: 'liverunxi',
    authDomain: 'liverunxi.firebaseapp.com',
    storageBucket: 'liverunxi.firebasestorage.app',
  );
}
